apiVersion: v1
kind: Secret
metadata:
  name: secret-properties-api-persona
type: Opaque
stringData:
  host: "cip-hd-bd.name2.svc.cluster.local"
  port: "3306"
  database: "demobd"
  username: "root"
  password: "toor"
