apiVersion: v1
kind: Service
metadata:
  name: lb-api-persona
spec:
  type: LoadBalancer
  selector:
    app: api-persona
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

# browser -> load-balancer-address:60000