apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-api-persona
  labels:
    app: rs-api-persona
spec:
  replicas: 2 # el comando rollout funciona con rs pero no con rc
  selector: #esta feature hace la diferencia con los RC (replication controller)
    #pueden usar cualquier criterio de busq de pods
    matchLabels: 
      app: api-persona
  # especificacion del pod
  template:
    metadata:
      labels:
        app: api-persona
    spec:
      containers:
      - image: jcontrerasp/img-api-persona
        name: api-persona
        envFrom:
        - configMapRef:
            name: configmap-properties-api-persona
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always