apiVersion: v1 #versión
kind: Service #tipo de componente
metadata:
  name: cip-api-persona #nombre del cluster
spec:
  type: ClusterIP
  selector: #Busca todas los pods con los siguientes criterios para exponerlos
    app: api-persona # busca por label app con valor api-bd
  ports:
  - protocol: TCP
    port: 8080 #Puerto a exponer
    targetPort: 8080 #puertos que usan los pods

