apiVersion: v1
kind: Pod
metadata:
  name: stack-api-persona
  labels:
    app: api-persona
    version: v1
spec:
  containers:
   - name: api-persona 
     image: jcontrerasp/img-api-persona
     ports:
        - containerPort: 8080
     env:
        - name: host
          value: localhost
        - name: port
          value: "3306"
   - name: bd
     image: jcontrerasp/img-base-de-datos
     ports:
        - containerPort: 3306
  restartPolicy: OnFailure #valores posibles -> Always, OnFailure, Never
